<?php

declare(strict_types=1);

namespace BAGArt\ProxyOperations\Models;

use BAGArt\ProxyOperations\Database\Factories\PolicySnapshotFactory;
use BAGArt\ProxyOperations\Domain\Snapshot\AuditPolicySnapshot;
use BAGArt\ProxyOperations\Models\Concerns\BelongsToTenant;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Durable PolicySnapshot row (plan §§11.18, 11.21, 11.35 п.7): the frozen
 * AuditPolicySnapshot DTO (T93) persisted so a job survives Redis loss —
 * Postgres is the domain truth (INV-003). Retention/UI/export flags never
 * enter a snapshot. Rows are immutable after create: any mutation attempt
 * raises ImmutableRecordException (same pattern as ProxyObservation, T07).
 *
 * @property string $id
 * @property int $tenant_id
 * @property int $policy_version
 * @property array<string, mixed> $snapshot
 */
final class PolicySnapshot extends Model
{
    use BelongsToTenant;
    use HasFactory;
    use HasUuids;

    protected $fillable = [
        'policy_version',
        'snapshot',
    ];

    // Immutable: created_at is stamped on insert; there is no updated_at.
    public const UPDATED_AT = null;

    protected static function booted(): void
    {
        self::updating(function (): void {
            throw new ImmutableRecordException('Policy snapshots are immutable and must not be updated.');
        });

        self::deleting(function (): void {
            throw new ImmutableRecordException('Policy snapshots are immutable and must not be deleted.');
        });
    }

    /**
     * Deserialize the stored payload back into the immutable DTO.
     */
    public function toDto(): AuditPolicySnapshot
    {
        return AuditPolicySnapshot::fromJson(
            is_array($this->snapshot) ? $this->snapshot : [],
        );
    }

    /**
     * Bridge a DTO into a persistable row. The row id is generated by the
     * model; the DTO keeps its own stable snapshot id inside the JSON payload.
     */
    public static function fromDto(AuditPolicySnapshot $snapshot): self
    {
        return self::create([
            'policy_version' => $snapshot->policyVersion,
            'snapshot' => $snapshot->jsonSerialize(),
        ]);
    }

    protected function casts(): array
    {
        return [
            'policy_version' => 'integer',
            'snapshot' => 'array',
        ];
    }

    protected static function newFactory(): Factory
    {
        return PolicySnapshotFactory::new();
    }
}
